######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 28 15:46:15 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += prog.h
SOURCES += main.cpp prog.cpp
